Changed package to noarch
SUSE/salt-formulas pull request #135
Opened 2021-07-16 05:38 UTC by sbluhm

Changed package to "noarch". This omits trying to build a debug package which would fail on EL builds due to missing binaries.

2021-07-30 13:29 UTC, sbluhm commented
@renner /@juliogonzalez can you please review/merge?

2021-07-30 13:41 UTC, juliogonzalez commented
Adding reviewers. Change looks OK, but I am not sure if there are unintended consequences :-)

2021-07-30 13:48 UTC, witekest approved these changes
Looks good to me. I think we don't need version number bump here.

2021-07-30 13:52 UTC, aaannz approved these changes
👍🏾 
I am not sure how is the release procedure here. But if this is similar to retail, I am not sure if version bump is not required as well. Sideeffect having spec in git and using obs  _service.

2021-07-30 13:55 UTC, aaannz commented
@agraul Any thought?

2021-08-02 09:23 UTC, agraul requested changes
> @agraul Any thought?

You're right, we to bump the spec to 0.1.2 and `git tag` it with `openvpn-v0.1.2` after merging  this PR. 

I left suggestions that do the changes for the spec and the changlog file inline.

2021-08-02 09:23 UTC, agraul commented on openvpn-formula/openvpn-formula.spec
>  Version:        0.1.1
```suggestion
Version:        0.1.2
```

2021-08-02 09:23 UTC, agraul commented on openvpn-formula/openvpn-formula.changes
> +- Changed package to noarch.
```suggestion
- Update to v0.1.2
- Changed package to noarch.
```

2021-08-02 09:27 UTC, sbluhm reviewed
Done

2021-08-02 11:17 UTC, agraul approved these changes
Thanks! I will merge, tag and create a SR later.

2021-08-04 13:25 UTC, merged