Add support for Prometheus>=2.31
SUSE/salt-formulas pull request #156
Opened 2021-12-03 09:21 UTC by witekest

Prometheus 2.31 includes upstream Uyuni SD with different configuration options and different set of returned labels.
This change checks the version of the installed Prometheus package and applies the appropriate configuration template to provide unchanged user experience.

2021-12-03 13:23 UTC, juliogonzalez requested changes
Reviewed the changelog, codeitself is for @renner

2021-12-03 13:23 UTC, juliogonzalez commented on prometheus-formula/prometheus-formula.changes
> +- Add support for new Uyuni SD in Prometheus>=2.31
```suggestion
  * Add support for new Uyuni SD in Prometheus >= 2.31 
```
As I guess you will later add a version on top :-)

2021-12-03 15:07 UTC, juliogonzalez approved these changes
Changelog looks good. Code review is on @renner :-)

2021-12-08 16:35 UTC, renner approved these changes
It's hard for me to actually prove the correctness of the config files, but overall the code looks very good to me. Thanks Witek!

2021-12-09 12:55 UTC, merged